In [1]:
import numpy as np


In [3]:
def cost_function(X, y, w):
    m = len(y)
    J = (1/(2*m)) * np.sum(np.square(np.dot(X, w) - y))
    return J

def gradient(X, y, w):
    m = len(y)
    grad = (1/m) * np.dot(X.T, np.dot(X, w) - y)
    return grad

def BGD(X, y, w, alpha, iterations):
    m = len(y)
    J_history = np.zeros(iterations)

    for i in range(iterations):
        h = np.dot(X, w)
        w = w - alpha * gradient(X, y, w)
        J_history[i] = cost_function(X, y, w)
        print(w)

    return w, J_history


In [6]:
# Datos de entrenamiento
X = np.array([[1,1,1],[1,2,3],[1,3,5]])
y = np.array([5,13,21])

# Parámetros de la regresión lineal
w = np.array([0.78, 1.88, 2.98])
alpha = 0.01
iterations = 3

# Entrenamiento del modelo
w_optimal, J_history = BGD(X, y, w, alpha, iterations)

# Imprimir los pesos óptimos
print("Los pesos óptimos son: ", w_optimal)

[0.7752     1.87146667 2.96773333]
[0.77098667 1.86432711 2.95766756]
[0.76726023 1.85834316 2.94942609]
Los pesos óptimos son:  [0.76726023 1.85834316 2.94942609]
